/*
 * CTF Management API
 * API for managing CTF (Capture The Flag) games, teams, users, and services.
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.60
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The AuthSignInBody model module.
 * @module model/AuthSignInBody
 * @version 1.1.0
 */
export default class AuthSignInBody {
  /**
   * Constructs a new <code>AuthSignInBody</code>.
   * @alias module:model/AuthSignInBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AuthSignInBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthSignInBody} obj Optional instance to populate.
   * @return {module:model/AuthSignInBody} The populated <code>AuthSignInBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AuthSignInBody();
      if (data.hasOwnProperty('user_name'))
        obj.userName = ApiClient.convertToType(data['user_name'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} userName
 */
AuthSignInBody.prototype.userName = undefined;

/**
 * @member {String} password
 */
AuthSignInBody.prototype.password = undefined;

