/*
 * CTF Management API
 * API for managing CTF (Capture The Flag) games, teams, users, and services.
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.60
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The GameResponse model module.
 * @module model/GameResponse
 * @version 1.1.0
 */
export default class GameResponse {
  /**
   * Constructs a new <code>GameResponse</code>.
   * @alias module:model/GameResponse
   * @class
   * @param id {String} Unique identifier for the game
   * @param startTime {Date} The start time of the game
   * @param endTime {Date} The end time of the game
   */
  constructor(id, startTime, endTime) {
    this.id = id;
    this.startTime = startTime;
    this.endTime = endTime;
  }

  /**
   * Constructs a <code>GameResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GameResponse} obj Optional instance to populate.
   * @return {module:model/GameResponse} The populated <code>GameResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GameResponse();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('start_time'))
        obj.startTime = ApiClient.convertToType(data['start_time'], 'Date');
      if (data.hasOwnProperty('end_time'))
        obj.endTime = ApiClient.convertToType(data['end_time'], 'Date');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * Unique identifier for the game
 * @member {String} id
 */
GameResponse.prototype.id = undefined;

/**
 * The start time of the game
 * @member {Date} startTime
 */
GameResponse.prototype.startTime = undefined;

/**
 * The end time of the game
 * @member {Date} endTime
 */
GameResponse.prototype.endTime = undefined;

/**
 * A brief description of the game
 * @member {String} description
 */
GameResponse.prototype.description = undefined;

