/*
 * CTF Management API
 * API for managing CTF (Capture The Flag) games, teams, users, and services.
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.60
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import TeamHistory from './TeamHistory';

/**
 * The ProfileResponse model module.
 * @module model/ProfileResponse
 * @version 1.1.0
 */
export default class ProfileResponse {
  /**
   * Constructs a new <code>ProfileResponse</code>.
   * The response schema for a user&#x27;s profile, including id, timestamps, team name, and team history.
   * @alias module:model/ProfileResponse
   * @class
   * @param id {String} The unique identifier for the user.
   * @param createdAt {Date} The timestamp when the user profile was created.
   * @param teamName {String} The current name of the user's team.
   * @param teamRole {module:model/ProfileResponse.TeamRoleEnum} The current role of the user's team.
   */
  constructor(id, createdAt, teamName, teamRole) {
    this.id = id;
    this.createdAt = createdAt;
    this.teamName = teamName;
    this.teamRole = teamRole;
  }

  /**
   * Constructs a <code>ProfileResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProfileResponse} obj Optional instance to populate.
   * @return {module:model/ProfileResponse} The populated <code>ProfileResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProfileResponse();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'Date');
      if (data.hasOwnProperty('updated_at'))
        obj.updatedAt = ApiClient.convertToType(data['updated_at'], 'Date');
      if (data.hasOwnProperty('team_name'))
        obj.teamName = ApiClient.convertToType(data['team_name'], 'String');
      if (data.hasOwnProperty('team_role'))
        obj.teamRole = ApiClient.convertToType(data['team_role'], 'String');
      if (data.hasOwnProperty('team_history'))
        obj.teamHistory = ApiClient.convertToType(data['team_history'], [TeamHistory]);
    }
    return obj;
  }
}

/**
 * The unique identifier for the user.
 * @member {String} id
 */
ProfileResponse.prototype.id = undefined;

/**
 * The timestamp when the user profile was created.
 * @member {Date} createdAt
 */
ProfileResponse.prototype.createdAt = undefined;

/**
 * The timestamp when the user profile was last updated.
 * @member {Date} updatedAt
 */
ProfileResponse.prototype.updatedAt = undefined;

/**
 * The current name of the user's team.
 * @member {String} teamName
 */
ProfileResponse.prototype.teamName = undefined;

/**
 * Allowed values for the <code>teamRole</code> property.
 * @enum {String}
 * @readonly
 */
ProfileResponse.TeamRoleEnum = {
  /**
   * value: "owner"
   * @const
   */
  owner: "owner",

  /**
   * value: "captain"
   * @const
   */
  captain: "captain",

  /**
   * value: "vice-captain"
   * @const
   */
  viceCaptain: "vice-captain",

  /**
   * value: "player"
   * @const
   */
  player: "player",

  /**
   * value: "guest"
   * @const
   */
  guest: "guest"
};
/**
 * The current role of the user's team.
 * @member {module:model/ProfileResponse.TeamRoleEnum} teamRole
 */
ProfileResponse.prototype.teamRole = undefined;

/**
 * The list of teams the user has been part of, including the periods of membership.
 * @member {Array.<module:model/TeamHistory>} teamHistory
 */
ProfileResponse.prototype.teamHistory = undefined;

