/*
 * CTF Management API
 * API for managing CTF (Capture The Flag) games, teams, users, and services.
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.60
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ServiceRequest model module.
 * @module model/ServiceRequest
 * @version 1.1.0
 */
export default class ServiceRequest {
  /**
   * Constructs a new <code>ServiceRequest</code>.
   * @alias module:model/ServiceRequest
   * @class
   * @param name {String} Name of the service
   * @param author {String} Author of the service
   * @param isPublic {Boolean} Boolean indicating if the service is public
   */
  constructor(name, author, isPublic) {
    this.name = name;
    this.author = author;
    this.isPublic = isPublic;
  }

  /**
   * Constructs a <code>ServiceRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ServiceRequest} obj Optional instance to populate.
   * @return {module:model/ServiceRequest} The populated <code>ServiceRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ServiceRequest();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('author'))
        obj.author = ApiClient.convertToType(data['author'], 'String');
      if (data.hasOwnProperty('logo_url'))
        obj.logoUrl = ApiClient.convertToType(data['logo_url'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('is_public'))
        obj.isPublic = ApiClient.convertToType(data['is_public'], 'Boolean');
    }
    return obj;
  }
}

/**
 * Name of the service
 * @member {String} name
 */
ServiceRequest.prototype.name = undefined;

/**
 * Author of the service
 * @member {String} author
 */
ServiceRequest.prototype.author = undefined;

/**
 * URL to the logo of the service
 * @member {String} logoUrl
 */
ServiceRequest.prototype.logoUrl = undefined;

/**
 * A brief description of the service
 * @member {String} description
 */
ServiceRequest.prototype.description = undefined;

/**
 * Boolean indicating if the service is public
 * @member {Boolean} isPublic
 */
ServiceRequest.prototype.isPublic = undefined;

