/*
 * CTF Management API
 * API for managing CTF (Capture The Flag) games, teams, users, and services.
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.60
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ServiceIdCheckerBody model module.
 * @module model/ServiceIdCheckerBody
 * @version 1.1.0
 */
export default class ServiceIdCheckerBody {
  /**
   * Constructs a new <code>ServiceIdCheckerBody</code>.
   * @alias module:model/ServiceIdCheckerBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ServiceIdCheckerBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ServiceIdCheckerBody} obj Optional instance to populate.
   * @return {module:model/ServiceIdCheckerBody} The populated <code>ServiceIdCheckerBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ServiceIdCheckerBody();
      if (data.hasOwnProperty('file'))
        obj.file = ApiClient.convertToType(data['file'], 'Blob');
    }
    return obj;
  }
}

/**
 * @member {Blob} file
 */
ServiceIdCheckerBody.prototype.file = undefined;

