/*
 * CTF Management API
 * API for managing CTF (Capture The Flag) games, teams, users, and services.
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.60
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SessionResponse model module.
 * @module model/SessionResponse
 * @version 1.1.0
 */
export default class SessionResponse {
  /**
   * Constructs a new <code>SessionResponse</code>.
   * @alias module:model/SessionResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SessionResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SessionResponse} obj Optional instance to populate.
   * @return {module:model/SessionResponse} The populated <code>SessionResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SessionResponse();
      if (data.hasOwnProperty('role'))
        obj.role = ApiClient.convertToType(data['role'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
    }
    return obj;
  }
}

/**
 * The role of the current user
 * @member {String} role
 */
SessionResponse.prototype.role = undefined;

/**
 * The name of the current user
 * @member {String} name
 */
SessionResponse.prototype.name = undefined;

/**
 * @member {String} id
 */
SessionResponse.prototype.id = undefined;

