/*
 * CTF Management API
 * API for managing CTF (Capture The Flag) games, teams, users, and services.
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.60
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TeamRequest model module.
 * @module model/TeamRequest
 * @version 1.1.0
 */
export default class TeamRequest {
  /**
   * Constructs a new <code>TeamRequest</code>.
   * @alias module:model/TeamRequest
   * @class
   * @param name {String} Name of the team
   * @param universityId {String} University or institution the team is associated with
   */
  constructor(name, universityId) {
    this.name = name;
    this.universityId = universityId;
  }

  /**
   * Constructs a <code>TeamRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TeamRequest} obj Optional instance to populate.
   * @return {module:model/TeamRequest} The populated <code>TeamRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TeamRequest();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('university_id'))
        obj.universityId = ApiClient.convertToType(data['university_id'], 'String');
      if (data.hasOwnProperty('social_links'))
        obj.socialLinks = ApiClient.convertToType(data['social_links'], 'String');
      if (data.hasOwnProperty('avatar_url'))
        obj.avatarUrl = ApiClient.convertToType(data['avatar_url'], 'String');
    }
    return obj;
  }
}

/**
 * Name of the team
 * @member {String} name
 */
TeamRequest.prototype.name = undefined;

/**
 * A brief description of the team
 * @member {String} description
 */
TeamRequest.prototype.description = undefined;

/**
 * University or institution the team is associated with
 * @member {String} universityId
 */
TeamRequest.prototype.universityId = undefined;

/**
 * JSON string containing social media links of the team
 * @member {String} socialLinks
 */
TeamRequest.prototype.socialLinks = undefined;

/**
 * URL to the team's avatar
 * @member {String} avatarUrl
 */
TeamRequest.prototype.avatarUrl = undefined;

