/*
 * CTF Management API
 * API for managing CTF (Capture The Flag) games, teams, users, and services.
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.60
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TeamHistory model module.
 * @module model/TeamHistory
 * @version 1.1.0
 */
export default class TeamHistory {
  /**
   * Constructs a new <code>TeamHistory</code>.
   * The schema for recording the history of teams a user has joined and left.
   * @alias module:model/TeamHistory
   * @class
   * @param name {String} The name of the team.
   * @param role {module:model/TeamHistory.RoleEnum} Role of the user's team.
   * @param join {Date} The timestamp when the user joined the team.
   */
  constructor(name, role, join) {
    this.name = name;
    this.role = role;
    this.join = join;
  }

  /**
   * Constructs a <code>TeamHistory</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TeamHistory} obj Optional instance to populate.
   * @return {module:model/TeamHistory} The populated <code>TeamHistory</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TeamHistory();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('role'))
        obj.role = ApiClient.convertToType(data['role'], 'String');
      if (data.hasOwnProperty('join'))
        obj.join = ApiClient.convertToType(data['join'], 'Date');
      if (data.hasOwnProperty('left'))
        obj.left = ApiClient.convertToType(data['left'], 'Date');
    }
    return obj;
  }
}

/**
 * The name of the team.
 * @member {String} name
 */
TeamHistory.prototype.name = undefined;

/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
TeamHistory.RoleEnum = {
  /**
   * value: "owner"
   * @const
   */
  owner: "owner",

  /**
   * value: "captain"
   * @const
   */
  captain: "captain",

  /**
   * value: "vice-captain"
   * @const
   */
  viceCaptain: "vice-captain",

  /**
   * value: "player"
   * @const
   */
  player: "player",

  /**
   * value: "guest"
   * @const
   */
  guest: "guest"
};
/**
 * Role of the user's team.
 * @member {module:model/TeamHistory.RoleEnum} role
 */
TeamHistory.prototype.role = undefined;

/**
 * The timestamp when the user joined the team.
 * @member {Date} join
 */
TeamHistory.prototype.join = undefined;

/**
 * The timestamp when the user left the team.
 * @member {Date} left
 */
TeamHistory.prototype.left = undefined;

