/*
 * CTF Management API
 * API for managing CTF (Capture The Flag) games, teams, users, and services.
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.60
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TeamResponse model module.
 * @module model/TeamResponse
 * @version 1.1.0
 */
export default class TeamResponse {
  /**
   * Constructs a new <code>TeamResponse</code>.
   * @alias module:model/TeamResponse
   * @class
   * @param id {String} Unique identifier for the team
   * @param name {String} Name of the team
   */
  constructor(id, name) {
    this.id = id;
    this.name = name;
  }

  /**
   * Constructs a <code>TeamResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TeamResponse} obj Optional instance to populate.
   * @return {module:model/TeamResponse} The populated <code>TeamResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TeamResponse();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('university'))
        obj.university = ApiClient.convertToType(data['university'], 'String');
      if (data.hasOwnProperty('social_links'))
        obj.socialLinks = ApiClient.convertToType(data['social_links'], 'String');
      if (data.hasOwnProperty('avatar_url'))
        obj.avatarUrl = ApiClient.convertToType(data['avatar_url'], 'String');
    }
    return obj;
  }
}

/**
 * Unique identifier for the team
 * @member {String} id
 */
TeamResponse.prototype.id = undefined;

/**
 * Name of the team
 * @member {String} name
 */
TeamResponse.prototype.name = undefined;

/**
 * A brief description of the team
 * @member {String} description
 */
TeamResponse.prototype.description = undefined;

/**
 * University or institution the team is associated with
 * @member {String} university
 */
TeamResponse.prototype.university = undefined;

/**
 * JSON string containing social media links of the team
 * @member {String} socialLinks
 */
TeamResponse.prototype.socialLinks = undefined;

/**
 * URL to the team's avatar
 * @member {String} avatarUrl
 */
TeamResponse.prototype.avatarUrl = undefined;

