/*
 * CTF Management API
 * API for managing CTF (Capture The Flag) games, teams, users, and services.
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.60
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import UniversityResponse from './UniversityResponse';

/**
 * The UniversitiesResponse model module.
 * @module model/UniversitiesResponse
 * @version 1.1.0
 */
export default class UniversitiesResponse extends Array {
  /**
   * Constructs a new <code>UniversitiesResponse</code>.
   * @alias module:model/UniversitiesResponse
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>UniversitiesResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UniversitiesResponse} obj Optional instance to populate.
   * @return {module:model/UniversitiesResponse} The populated <code>UniversitiesResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UniversitiesResponse();
      ApiClient.constructFromObject(data, obj, 'UniversityResponse');
    }
    return obj;
  }
}
