/*
 * CTF Management API
 * API for managing CTF (Capture The Flag) games, teams, users, and services.
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.60
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UniversityResponse model module.
 * @module model/UniversityResponse
 * @version 1.1.0
 */
export default class UniversityResponse {
  /**
   * Constructs a new <code>UniversityResponse</code>.
   * @alias module:model/UniversityResponse
   * @class
   * @param id {String} The unique identifier of the university
   * @param name {String} The name of the university
   */
  constructor(id, name) {
    this.id = id;
    this.name = name;
  }

  /**
   * Constructs a <code>UniversityResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UniversityResponse} obj Optional instance to populate.
   * @return {module:model/UniversityResponse} The populated <code>UniversityResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UniversityResponse();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * The unique identifier of the university
 * @member {String} id
 */
UniversityResponse.prototype.id = undefined;

/**
 * The name of the university
 * @member {String} name
 */
UniversityResponse.prototype.name = undefined;

