/*
 * CTF Management API
 * API for managing CTF (Capture The Flag) games, teams, users, and services.
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.60
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import AuthSignInBody from './model/AuthSignInBody';
import CreateGameResponse from './model/CreateGameResponse';
import CreateResultResponse from './model/CreateResultResponse';
import CreateServiceResponse from './model/CreateServiceResponse';
import CreateTeamResponse from './model/CreateTeamResponse';
import CreateUserResponse from './model/CreateUserResponse';
import GameRequest from './model/GameRequest';
import GameResponse from './model/GameResponse';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import InlineResponse2002 from './model/InlineResponse2002';
import ProfileResponse from './model/ProfileResponse';
import ResultRequest from './model/ResultRequest';
import ResultResponse from './model/ResultResponse';
import ServiceIdCheckerBody from './model/ServiceIdCheckerBody';
import ServiceIdServiceBody from './model/ServiceIdServiceBody';
import ServiceRequest from './model/ServiceRequest';
import ServiceResponse from './model/ServiceResponse';
import SessionResponse from './model/SessionResponse';
import TeamHistory from './model/TeamHistory';
import TeamRequest from './model/TeamRequest';
import TeamResponse from './model/TeamResponse';
import UniversitiesResponse from './model/UniversitiesResponse';
import UniversityResponse from './model/UniversityResponse';
import UserRequest from './model/UserRequest';
import UserResponse from './model/UserResponse';
import GamesApi from './api/GamesApi';
import ResultsApi from './api/ResultsApi';
import ServicesApi from './api/ServicesApi';
import SessionsApi from './api/SessionsApi';
import TeamsApi from './api/TeamsApi';
import UniversityApi from './api/UniversityApi';
import UsersApi from './api/UsersApi';

/**
* API_for_managing_CTF__Capture_The_Flag_games_teams_users_and_services_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var CtfManagementApi = require('index'); // See note below*.
* var xxxSvc = new CtfManagementApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new CtfManagementApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new CtfManagementApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new CtfManagementApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuthSignInBody model constructor.
     * @property {module:model/AuthSignInBody}
     */
    AuthSignInBody,

    /**
     * The CreateGameResponse model constructor.
     * @property {module:model/CreateGameResponse}
     */
    CreateGameResponse,

    /**
     * The CreateResultResponse model constructor.
     * @property {module:model/CreateResultResponse}
     */
    CreateResultResponse,

    /**
     * The CreateServiceResponse model constructor.
     * @property {module:model/CreateServiceResponse}
     */
    CreateServiceResponse,

    /**
     * The CreateTeamResponse model constructor.
     * @property {module:model/CreateTeamResponse}
     */
    CreateTeamResponse,

    /**
     * The CreateUserResponse model constructor.
     * @property {module:model/CreateUserResponse}
     */
    CreateUserResponse,

    /**
     * The GameRequest model constructor.
     * @property {module:model/GameRequest}
     */
    GameRequest,

    /**
     * The GameResponse model constructor.
     * @property {module:model/GameResponse}
     */
    GameResponse,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The ProfileResponse model constructor.
     * @property {module:model/ProfileResponse}
     */
    ProfileResponse,

    /**
     * The ResultRequest model constructor.
     * @property {module:model/ResultRequest}
     */
    ResultRequest,

    /**
     * The ResultResponse model constructor.
     * @property {module:model/ResultResponse}
     */
    ResultResponse,

    /**
     * The ServiceIdCheckerBody model constructor.
     * @property {module:model/ServiceIdCheckerBody}
     */
    ServiceIdCheckerBody,

    /**
     * The ServiceIdServiceBody model constructor.
     * @property {module:model/ServiceIdServiceBody}
     */
    ServiceIdServiceBody,

    /**
     * The ServiceRequest model constructor.
     * @property {module:model/ServiceRequest}
     */
    ServiceRequest,

    /**
     * The ServiceResponse model constructor.
     * @property {module:model/ServiceResponse}
     */
    ServiceResponse,

    /**
     * The SessionResponse model constructor.
     * @property {module:model/SessionResponse}
     */
    SessionResponse,

    /**
     * The TeamHistory model constructor.
     * @property {module:model/TeamHistory}
     */
    TeamHistory,

    /**
     * The TeamRequest model constructor.
     * @property {module:model/TeamRequest}
     */
    TeamRequest,

    /**
     * The TeamResponse model constructor.
     * @property {module:model/TeamResponse}
     */
    TeamResponse,

    /**
     * The UniversitiesResponse model constructor.
     * @property {module:model/UniversitiesResponse}
     */
    UniversitiesResponse,

    /**
     * The UniversityResponse model constructor.
     * @property {module:model/UniversityResponse}
     */
    UniversityResponse,

    /**
     * The UserRequest model constructor.
     * @property {module:model/UserRequest}
     */
    UserRequest,

    /**
     * The UserResponse model constructor.
     * @property {module:model/UserResponse}
     */
    UserResponse,

    /**
    * The GamesApi service constructor.
    * @property {module:api/GamesApi}
    */
    GamesApi,

    /**
    * The ResultsApi service constructor.
    * @property {module:api/ResultsApi}
    */
    ResultsApi,

    /**
    * The ServicesApi service constructor.
    * @property {module:api/ServicesApi}
    */
    ServicesApi,

    /**
    * The SessionsApi service constructor.
    * @property {module:api/SessionsApi}
    */
    SessionsApi,

    /**
    * The TeamsApi service constructor.
    * @property {module:api/TeamsApi}
    */
    TeamsApi,

    /**
    * The UniversityApi service constructor.
    * @property {module:api/UniversityApi}
    */
    UniversityApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
