/*
 * CTF Management API
 * API for managing CTF (Capture The Flag) games, teams, users, and services.
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.60
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CtfManagementApi);
  }
}(this, function(expect, CtfManagementApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ProfileResponse', function() {
      beforeEach(function() {
        instance = new CtfManagementApi.ProfileResponse();
      });

      it('should create an instance of ProfileResponse', function() {
        // TODO: update the code to test ProfileResponse
        expect(instance).to.be.a(CtfManagementApi.ProfileResponse);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property createdAt (base name: "created_at")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

      it('should have the property updatedAt (base name: "updated_at")', function() {
        // TODO: update the code to test the property updatedAt
        expect(instance).to.have.property('updatedAt');
        // expect(instance.updatedAt).to.be(expectedValueLiteral);
      });

      it('should have the property teamName (base name: "team_name")', function() {
        // TODO: update the code to test the property teamName
        expect(instance).to.have.property('teamName');
        // expect(instance.teamName).to.be(expectedValueLiteral);
      });

      it('should have the property teamRole (base name: "team_role")', function() {
        // TODO: update the code to test the property teamRole
        expect(instance).to.have.property('teamRole');
        // expect(instance.teamRole).to.be(expectedValueLiteral);
      });

      it('should have the property teamHistory (base name: "team_history")', function() {
        // TODO: update the code to test the property teamHistory
        expect(instance).to.have.property('teamHistory');
        // expect(instance.teamHistory).to.be(expectedValueLiteral);
      });

    });
  });

}));
