/*
 * CTF Management API
 * API for managing CTF (Capture The Flag) games, teams, users, and services.
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.60
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CtfManagementApi);
  }
}(this, function(expect, CtfManagementApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TeamHistory', function() {
      beforeEach(function() {
        instance = new CtfManagementApi.TeamHistory();
      });

      it('should create an instance of TeamHistory', function() {
        // TODO: update the code to test TeamHistory
        expect(instance).to.be.a(CtfManagementApi.TeamHistory);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property role (base name: "role")', function() {
        // TODO: update the code to test the property role
        expect(instance).to.have.property('role');
        // expect(instance.role).to.be(expectedValueLiteral);
      });

      it('should have the property join (base name: "join")', function() {
        // TODO: update the code to test the property join
        expect(instance).to.have.property('join');
        // expect(instance.join).to.be(expectedValueLiteral);
      });

      it('should have the property left (base name: "left")', function() {
        // TODO: update the code to test the property left
        expect(instance).to.have.property('left');
        // expect(instance.left).to.be(expectedValueLiteral);
      });

    });
  });

}));
