/*
 * CTF Management API
 * API for managing CTF (Capture The Flag) games, teams, users, and services.
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.60
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CtfManagementApi);
  }
}(this, function(expect, CtfManagementApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('UserRequest', function() {
      beforeEach(function() {
        instance = new CtfManagementApi.UserRequest();
      });

      it('should create an instance of UserRequest', function() {
        // TODO: update the code to test UserRequest
        expect(instance).to.be.a(CtfManagementApi.UserRequest);
      });

      it('should have the property displayName (base name: "display_name")', function() {
        // TODO: update the code to test the property displayName
        expect(instance).to.have.property('displayName');
        // expect(instance.displayName).to.be(expectedValueLiteral);
      });

      it('should have the property userName (base name: "user_name")', function() {
        // TODO: update the code to test the property userName
        expect(instance).to.have.property('userName');
        // expect(instance.userName).to.be(expectedValueLiteral);
      });

      it('should have the property role (base name: "role")', function() {
        // TODO: update the code to test the property role
        expect(instance).to.have.property('role');
        // expect(instance.role).to.be(expectedValueLiteral);
      });

      it('should have the property avatarUrl (base name: "avatar_url")', function() {
        // TODO: update the code to test the property avatarUrl
        expect(instance).to.have.property('avatarUrl');
        // expect(instance.avatarUrl).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property password (base name: "password")', function() {
        // TODO: update the code to test the property password
        expect(instance).to.have.property('password');
        // expect(instance.password).to.be(expectedValueLiteral);
      });

      it('should have the property teamIds (base name: "team_ids")', function() {
        // TODO: update the code to test the property teamIds
        expect(instance).to.have.property('teamIds');
        // expect(instance.teamIds).to.be(expectedValueLiteral);
      });

    });
  });

}));
